version: "3.8"

services:
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    image: xiaopeng163/flask-redis:latest
    ports:
      - "8080:5000"
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PASS=${REDIS_PASSWORD}


  redis-server:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
